### ISSUE TITLE
Partner Agency Login

### ISSUE THREAD

**Issue by katiesteiner** [rubyforgood/diaperpartner#1]
As a diaperbase admin I'd like be able to invite partner agencies to login to a Diaper Partner Portal.

As a partner agency, I'd like to be able use the invite from the diaperbase admin to login to Diaper Partner Portal.

**Comment by dukedave** [comment]
Linked to https://github.com/rubyforgood/diaper/issues/224 on the _other side_.

**Comment by dukedave** [comment]
I have started on this.
1. Pulling in basic layout from https://github.com/rubyforgood/diaper
1. I'll use Devise for auth'ing a `Partner`
1. I'll add an endpoint for Diaperbase to `POST` to, which will create a `Partner`.

I'll copy `Partner` from here:
https://github.com/rubyforgood/diaper/blob/6af38f5c8b98647ad2bfc42803ff8ac7e2e33643/db/schema.rb#L131-L138

**Comment by dukedave** [comment]
Okay, this is done in the most MVP way possible, it's essentially just this commit: 5b32a89c0efc02181f42339a8ba91a5fc61b1089

It's also blocked on the other side by this: https://github.com/rubyforgood/diaper/pull/291

At the moment it just creates a new partner with the same email as in DiaperBase and the password `password`.  You can then log in with this at `/partners/sign_in`.
